/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var peertopeer_PeerEndorsementAcquisition_pb = require('./peertopeer/PeerEndorsementAcquisition_pb.js');
goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence', null, global);
goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences', null, global);
goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.repeatedFields_, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.displayName = 'proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.toObject = function(includeInstance, msg) {
  var f, obj = {
    evidencesList: jspb.Message.toObjectList(msg.getEvidencesList(),
    proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences;
  return proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence;
      reader.readMessage(value,proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.deserializeBinaryFromReader);
      msg.addEvidences(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEvidencesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.serializeBinaryToWriter
    );
  }
};


/**
 * repeated VisitEvidence evidences = 1;
 * @return {!Array<!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence>}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.prototype.getEvidencesList = function() {
  return /** @type{!Array<!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence, 1));
};


/** @param {!Array<!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence>} value */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.prototype.setEvidencesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.prototype.addEvidences = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence, opt_index);
};


proto.pt.ulisboa.tecnico.cross.contract.VisitEvidences.prototype.clearEvidencesList = function() {
  this.setEvidencesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.oneofGroups_);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.displayName = 'proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.EvidenceCase = {
  EVIDENCE_NOT_SET: 0,
  WIFIAPEVIDENCE: 1,
  PEERENDORSEMENT: 2
};

/**
 * @return {proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.EvidenceCase}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.getEvidenceCase = function() {
  return /** @type {proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.EvidenceCase} */(jspb.Message.computeOneofCase(this, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.toObject = function(includeInstance, msg) {
  var f, obj = {
    wifiapevidence: (f = msg.getWifiapevidence()) && proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.toObject(includeInstance, f),
    peerendorsement: (f = msg.getPeerendorsement()) && peertopeer_PeerEndorsementAcquisition_pb.PeerEndorsement.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence;
  return proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence;
      reader.readMessage(value,proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.deserializeBinaryFromReader);
      msg.setWifiapevidence(value);
      break;
    case 2:
      var value = new peertopeer_PeerEndorsementAcquisition_pb.PeerEndorsement;
      reader.readMessage(value,peertopeer_PeerEndorsementAcquisition_pb.PeerEndorsement.deserializeBinaryFromReader);
      msg.setPeerendorsement(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWifiapevidence();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.serializeBinaryToWriter
    );
  }
  f = message.getPeerendorsement();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      peertopeer_PeerEndorsementAcquisition_pb.PeerEndorsement.serializeBinaryToWriter
    );
  }
};


/**
 * optional WiFiAPEvidence wiFiAPEvidence = 1;
 * @return {?proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.getWifiapevidence = function() {
  return /** @type{?proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence} */ (
    jspb.Message.getWrapperField(this, proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence, 1));
};


/** @param {?proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence|undefined} value */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.setWifiapevidence = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.oneofGroups_[0], value);
};


proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.clearWifiapevidence = function() {
  this.setWifiapevidence(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.hasWifiapevidence = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional pt.ulisboa.tecnico.cross.peertopeer.PeerEndorsement peerEndorsement = 2;
 * @return {?proto.pt.ulisboa.tecnico.cross.peertopeer.PeerEndorsement}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.getPeerendorsement = function() {
  return /** @type{?proto.pt.ulisboa.tecnico.cross.peertopeer.PeerEndorsement} */ (
    jspb.Message.getWrapperField(this, peertopeer_PeerEndorsementAcquisition_pb.PeerEndorsement, 2));
};


/** @param {?proto.pt.ulisboa.tecnico.cross.peertopeer.PeerEndorsement|undefined} value */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.setPeerendorsement = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.oneofGroups_[0], value);
};


proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.clearPeerendorsement = function() {
  this.setPeerendorsement(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.pt.ulisboa.tecnico.cross.contract.VisitEvidence.prototype.hasPeerendorsement = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.displayName = 'proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.toObject = function(includeInstance, msg) {
  var f, obj = {
    bssid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    ssid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sightingmillis: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence;
  return proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setBssid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSsid(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSightingmillis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBssid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSsid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSightingmillis();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
};


/**
 * optional string bssid = 1;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.getBssid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.setBssid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string ssid = 2;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.getSsid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.setSsid = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 sightingMillis = 3;
 * @return {number}
 */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.getSightingmillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.pt.ulisboa.tecnico.cross.contract.WiFiAPEvidence.prototype.setSightingmillis = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.pt.ulisboa.tecnico.cross.contract);
