/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest', null, global);
goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse', null, global);
goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.contract.POI', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.contract.POI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pt.ulisboa.tecnico.cross.contract.POI.repeatedFields_, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.contract.POI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.contract.POI.displayName = 'proto.pt.ulisboa.tecnico.cross.contract.POI';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.contract.POI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.POI} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    worldcoordList: jspb.Message.getRepeatedFloatingPointField(msg, 2),
    weburl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    imageurl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    mainlocale: jspb.Message.getFieldWithDefault(msg, 5, ""),
    namesMap: (f = msg.getNamesMap()) ? f.toObject(includeInstance, undefined) : [],
    descriptionsMap: (f = msg.getDescriptionsMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.POI}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.contract.POI;
  return proto.pt.ulisboa.tecnico.cross.contract.POI.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.POI} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.POI}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {!Array<number>} */ (reader.readPackedDouble());
      msg.setWorldcoordList(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setWeburl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageurl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainlocale(value);
      break;
    case 6:
      var value = msg.getNamesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "");
         });
      break;
    case 7:
      var value = msg.getDescriptionsMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.contract.POI.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.POI} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getWorldcoordList();
  if (f.length > 0) {
    writer.writePackedDouble(
      2,
      f
    );
  }
  f = message.getWeburl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getImageurl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMainlocale();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getNamesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(6, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
  f = message.getDescriptionsMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated double worldCoord = 2;
 * @return {!Array<number>}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getWorldcoordList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/** @param {!Array<number>} value */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.setWorldcoordList = function(value) {
  jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.addWorldcoord = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.clearWorldcoordList = function() {
  this.setWorldcoordList([]);
};


/**
 * optional string webURL = 3;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getWeburl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.setWeburl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string imageURL = 4;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getImageurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.setImageurl = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string mainLocale = 5;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getMainlocale = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.setMainlocale = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * map<string, string> names = 6;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getNamesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 6, opt_noLazyCreate,
      null));
};


proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.clearNamesMap = function() {
  this.getNamesMap().clear();
};


/**
 * map<string, string> descriptions = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.getDescriptionsMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      null));
};


proto.pt.ulisboa.tecnico.cross.contract.POI.prototype.clearDescriptionsMap = function() {
  this.getDescriptionsMap().clear();
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.repeatedFields_, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.displayName = 'proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    poisList: jspb.Message.toObjectList(msg.getPoisList(),
    proto.pt.ulisboa.tecnico.cross.contract.POI.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse;
  return proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.pt.ulisboa.tecnico.cross.contract.POI;
      reader.readMessage(value,proto.pt.ulisboa.tecnico.cross.contract.POI.deserializeBinaryFromReader);
      msg.addPois(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPoisList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.pt.ulisboa.tecnico.cross.contract.POI.serializeBinaryToWriter
    );
  }
};


/**
 * repeated POI POIs = 2;
 * @return {!Array<!proto.pt.ulisboa.tecnico.cross.contract.POI>}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.prototype.getPoisList = function() {
  return /** @type{!Array<!proto.pt.ulisboa.tecnico.cross.contract.POI>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pt.ulisboa.tecnico.cross.contract.POI, 2));
};


/** @param {!Array<!proto.pt.ulisboa.tecnico.cross.contract.POI>} value */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.prototype.setPoisList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.POI=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.POI}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.prototype.addPois = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.pt.ulisboa.tecnico.cross.contract.POI, opt_index);
};


proto.pt.ulisboa.tecnico.cross.contract.GetPOIsResponse.prototype.clearPoisList = function() {
  this.setPoisList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.displayName = 'proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest;
  return proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.contract.GetPOIRequest.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.pt.ulisboa.tecnico.cross.contract);
