apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-deployment
  labels:
    app: cross-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cross-server
  template:
    metadata:
      labels:
        app: cross-server
    spec:
      containers:
      - name: cross-server
        image: cross-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - secretRef:
            name: cross-secret
        - configMapRef:
            name: cross-config
---
apiVersion: v1
kind: Service
metadata:
  name: cross-service
spec:
  type: NodePort
  selector:
    app: cross-server
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 30100
