kind: PersistentVolume
apiVersion: v1
metadata:
  name: psql-pv-volume
  labels:
    type: local
    app: cross-psql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-pv-claim
  labels:
    app: cross-psql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi