apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- files:
  - ./key.json
  name: cross-key
configMapGenerator:
- files:
  - ./1-schema.sql
  - ./2-populate.sql
  name: cross-psql-init
resources:
- psql-secret.yaml
- psql-pv.yaml
- psql.yaml
- cross-secret.yaml
- cross-config.yaml
- cross.yaml
- external-dns.yaml
- nginx-ingress.yaml
- cert-manager.yaml
- ca-key-pair.yaml
- ca-issuer.yaml
- cross-ingress.yaml
