apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-k6
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: cross-k6/crossplane
    repoURL: https://github.com/inesc-id/CROSSCityCloud
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc