apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-prometheus-crds
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-35.4.2
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - Replace=true
  destination:
    namespace: default
    server: https://34.76.123.249