apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 35.4.2
    helm:
      releaseName: main
      skipCrds: true
  destination:
    namespace: default
    server: https://34.76.123.249