/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation', null, global);
goog.exportSymbol('proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.displayName = 'proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.toObject = function(includeInstance, msg) {
  var f, obj = {
    traveler: jspb.Message.getFieldWithDefault(msg, 1, ""),
    poiid: jspb.Message.getFieldWithDefault(msg, 2, ""),
    bssid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sightingmillis: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation;
  return proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraveler(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPoiid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setBssid(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setSightingmillis(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTraveler();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPoiid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getBssid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSightingmillis();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
};


/**
 * optional string traveler = 1;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.getTraveler = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.setTraveler = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string poiId = 2;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.getPoiid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.setPoiid = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string bssid = 3;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.getBssid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.setBssid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int64 sightingMillis = 4;
 * @return {number}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.getSightingmillis = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.prototype.setSightingmillis = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.repeatedFields_, null);
};
goog.inherits(proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.displayName = 'proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.toObject = function(opt_includeInstance) {
  return proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.toObject = function(includeInstance, msg) {
  var f, obj = {
    observationsList: jspb.Message.toObjectList(msg.getObservationsList(),
    proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.toObject, includeInstance),
    traveler: jspb.Message.getFieldWithDefault(msg, 2, ""),
    poiid: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList;
  return proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation;
      reader.readMessage(value,proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.deserializeBinaryFromReader);
      msg.addObservations(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraveler(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPoiid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getObservationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation.serializeBinaryToWriter
    );
  }
  f = message.getTraveler();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPoiid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * repeated WiFiAPObservation observations = 1;
 * @return {!Array<!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation>}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.getObservationsList = function() {
  return /** @type{!Array<!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation, 1));
};


/** @param {!Array<!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation>} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.setObservationsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.addObservations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservation, opt_index);
};


proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.clearObservationsList = function() {
  this.setObservationsList([]);
};


/**
 * optional string traveler = 2;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.getTraveler = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.setTraveler = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string poiId = 3;
 * @return {string}
 */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.getPoiid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.pt.ulisboa.tecnico.cross.scavenger.WiFiAPObservationList.prototype.setPoiid = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.pt.ulisboa.tecnico.cross.scavenger);
